/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 working_space.glb 
Author: Tochi-Tan (https://sketchfab.com/Tochi-Tan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/working-space-f407b224ac544e3ea9b0559c64fa7d20
Title: Working Space
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import model from "../assets/3Dmodels/working_space.glb";
export function WorkSpace(props) {
  const { nodes, materials } = useGLTF(model);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.palette}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
useGLTF.preload(model);
